// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/assets/bundle.proto

package tools.elide.assets;

public interface AssetBundleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assets.AssetBundle)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Version of the tool that produced this manifest. This is used by the tool to understand which asset bundle features
   * are supported for a given tool version.
   * </pre>
   *
   * <code>uint32 version = 1;</code>
   * @return The version.
   */
  int getVersion();

  /**
   * <pre>
   * Digest algorithm settings in use to calculate chunk tokens. These tokens are used to address pre-compressed asset
   * content, and are used to address assets dynamically from the server and frontend.
   * </pre>
   *
   * <code>.assets.AssetBundle.DigestSettings digest = 2;</code>
   * @return Whether the digest field is set.
   */
  boolean hasDigest();
  /**
   * <pre>
   * Digest algorithm settings in use to calculate chunk tokens. These tokens are used to address pre-compressed asset
   * content, and are used to address assets dynamically from the server and frontend.
   * </pre>
   *
   * <code>.assets.AssetBundle.DigestSettings digest = 2;</code>
   * @return The digest.
   */
  tools.elide.assets.AssetBundle.DigestSettings getDigest();
  /**
   * <pre>
   * Digest algorithm settings in use to calculate chunk tokens. These tokens are used to address pre-compressed asset
   * content, and are used to address assets dynamically from the server and frontend.
   * </pre>
   *
   * <code>.assets.AssetBundle.DigestSettings digest = 2;</code>
   */
  tools.elide.assets.AssetBundle.DigestSettingsOrBuilder getDigestOrBuilder();

  /**
   * <pre>
   * Set of styles listed in this asset manifest. Like scripts, this is a map of dotted-path module names mapped to
   * their stylesheet sources and settings. Generally, the GSS module name is used for stylesheets.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.StyleBundle&gt; styles = 3;</code>
   */
  int getStylesCount();
  /**
   * <pre>
   * Set of styles listed in this asset manifest. Like scripts, this is a map of dotted-path module names mapped to
   * their stylesheet sources and settings. Generally, the GSS module name is used for stylesheets.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.StyleBundle&gt; styles = 3;</code>
   */
  boolean containsStyles(
      java.lang.String key);
  /**
   * Use {@link #getStylesMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, tools.elide.assets.AssetBundle.StyleBundle>
  getStyles();
  /**
   * <pre>
   * Set of styles listed in this asset manifest. Like scripts, this is a map of dotted-path module names mapped to
   * their stylesheet sources and settings. Generally, the GSS module name is used for stylesheets.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.StyleBundle&gt; styles = 3;</code>
   */
  java.util.Map<java.lang.String, tools.elide.assets.AssetBundle.StyleBundle>
  getStylesMap();
  /**
   * <pre>
   * Set of styles listed in this asset manifest. Like scripts, this is a map of dotted-path module names mapped to
   * their stylesheet sources and settings. Generally, the GSS module name is used for stylesheets.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.StyleBundle&gt; styles = 3;</code>
   */

  /* nullable */
tools.elide.assets.AssetBundle.StyleBundle getStylesOrDefault(
      java.lang.String key,
      /* nullable */
tools.elide.assets.AssetBundle.StyleBundle defaultValue);
  /**
   * <pre>
   * Set of styles listed in this asset manifest. Like scripts, this is a map of dotted-path module names mapped to
   * their stylesheet sources and settings. Generally, the GSS module name is used for stylesheets.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.StyleBundle&gt; styles = 3;</code>
   */

  tools.elide.assets.AssetBundle.StyleBundle getStylesOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Set of scripts listed in this asset manifest. Like styles, this is a map of dotted-path module names mapped to
   * their script sources and settings. Generally, a Closure module name is used for scripts.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.ScriptBundle&gt; scripts = 4;</code>
   */
  int getScriptsCount();
  /**
   * <pre>
   * Set of scripts listed in this asset manifest. Like styles, this is a map of dotted-path module names mapped to
   * their script sources and settings. Generally, a Closure module name is used for scripts.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.ScriptBundle&gt; scripts = 4;</code>
   */
  boolean containsScripts(
      java.lang.String key);
  /**
   * Use {@link #getScriptsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, tools.elide.assets.AssetBundle.ScriptBundle>
  getScripts();
  /**
   * <pre>
   * Set of scripts listed in this asset manifest. Like styles, this is a map of dotted-path module names mapped to
   * their script sources and settings. Generally, a Closure module name is used for scripts.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.ScriptBundle&gt; scripts = 4;</code>
   */
  java.util.Map<java.lang.String, tools.elide.assets.AssetBundle.ScriptBundle>
  getScriptsMap();
  /**
   * <pre>
   * Set of scripts listed in this asset manifest. Like styles, this is a map of dotted-path module names mapped to
   * their script sources and settings. Generally, a Closure module name is used for scripts.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.ScriptBundle&gt; scripts = 4;</code>
   */

  /* nullable */
tools.elide.assets.AssetBundle.ScriptBundle getScriptsOrDefault(
      java.lang.String key,
      /* nullable */
tools.elide.assets.AssetBundle.ScriptBundle defaultValue);
  /**
   * <pre>
   * Set of scripts listed in this asset manifest. Like styles, this is a map of dotted-path module names mapped to
   * their script sources and settings. Generally, a Closure module name is used for scripts.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.ScriptBundle&gt; scripts = 4;</code>
   */

  tools.elide.assets.AssetBundle.ScriptBundle getScriptsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * Inlined asset contents, which specify pre-compressed asset data corresponding to a given CSS or JavaScript code
   * bundle. The server may choose to serve this content rather than performing compression on-the-fly.
   * </pre>
   *
   * <code>repeated .assets.AssetBundle.AssetContent asset = 5;</code>
   */
  java.util.List<tools.elide.assets.AssetBundle.AssetContent> 
      getAssetList();
  /**
   * <pre>
   * Inlined asset contents, which specify pre-compressed asset data corresponding to a given CSS or JavaScript code
   * bundle. The server may choose to serve this content rather than performing compression on-the-fly.
   * </pre>
   *
   * <code>repeated .assets.AssetBundle.AssetContent asset = 5;</code>
   */
  tools.elide.assets.AssetBundle.AssetContent getAsset(int index);
  /**
   * <pre>
   * Inlined asset contents, which specify pre-compressed asset data corresponding to a given CSS or JavaScript code
   * bundle. The server may choose to serve this content rather than performing compression on-the-fly.
   * </pre>
   *
   * <code>repeated .assets.AssetBundle.AssetContent asset = 5;</code>
   */
  int getAssetCount();
  /**
   * <pre>
   * Inlined asset contents, which specify pre-compressed asset data corresponding to a given CSS or JavaScript code
   * bundle. The server may choose to serve this content rather than performing compression on-the-fly.
   * </pre>
   *
   * <code>repeated .assets.AssetBundle.AssetContent asset = 5;</code>
   */
  java.util.List<? extends tools.elide.assets.AssetBundle.AssetContentOrBuilder> 
      getAssetOrBuilderList();
  /**
   * <pre>
   * Inlined asset contents, which specify pre-compressed asset data corresponding to a given CSS or JavaScript code
   * bundle. The server may choose to serve this content rather than performing compression on-the-fly.
   * </pre>
   *
   * <code>repeated .assets.AssetBundle.AssetContent asset = 5;</code>
   */
  tools.elide.assets.AssetBundle.AssetContentOrBuilder getAssetOrBuilder(
      int index);

  /**
   * <pre>
   * Timestamp indicating when this asset manifest was generated. This may be used when calculating `ETags` or when
   * checking for updates to the asset bundle itself.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp generated = 6;</code>
   * @return Whether the generated field is set.
   */
  boolean hasGenerated();
  /**
   * <pre>
   * Timestamp indicating when this asset manifest was generated. This may be used when calculating `ETags` or when
   * checking for updates to the asset bundle itself.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp generated = 6;</code>
   * @return The generated.
   */
  com.google.protobuf.Timestamp getGenerated();
  /**
   * <pre>
   * Timestamp indicating when this asset manifest was generated. This may be used when calculating `ETags` or when
   * checking for updates to the asset bundle itself.
   * </pre>
   *
   * <code>.google.protobuf.Timestamp generated = 6;</code>
   */
  com.google.protobuf.TimestampOrBuilder getGeneratedOrBuilder();

  /**
   * <pre>
   * Whether style-rewriting is enabled or not, which should indicate the presence of generated style symbol maps, that
   * must be loaded by the server for SSR.
   * </pre>
   *
   * <code>bool rewrite = 7;</code>
   * @return The rewrite.
   */
  boolean getRewrite();

  /**
   * <pre>
   * Generic assets which are mapped within this bundle.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.GenericBundle&gt; generic = 8;</code>
   */
  int getGenericCount();
  /**
   * <pre>
   * Generic assets which are mapped within this bundle.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.GenericBundle&gt; generic = 8;</code>
   */
  boolean containsGeneric(
      java.lang.String key);
  /**
   * Use {@link #getGenericMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, tools.elide.assets.AssetBundle.GenericBundle>
  getGeneric();
  /**
   * <pre>
   * Generic assets which are mapped within this bundle.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.GenericBundle&gt; generic = 8;</code>
   */
  java.util.Map<java.lang.String, tools.elide.assets.AssetBundle.GenericBundle>
  getGenericMap();
  /**
   * <pre>
   * Generic assets which are mapped within this bundle.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.GenericBundle&gt; generic = 8;</code>
   */

  /* nullable */
tools.elide.assets.AssetBundle.GenericBundle getGenericOrDefault(
      java.lang.String key,
      /* nullable */
tools.elide.assets.AssetBundle.GenericBundle defaultValue);
  /**
   * <pre>
   * Generic assets which are mapped within this bundle.
   * </pre>
   *
   * <code>map&lt;string, .assets.AssetBundle.GenericBundle&gt; generic = 8;</code>
   */

  tools.elide.assets.AssetBundle.GenericBundle getGenericOrThrow(
      java.lang.String key);
}
