// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/assets/embedded.proto

package tools.elide.assets;

public interface EmbeddedScriptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assets.EmbeddedScript)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>string module = 1;</code>
   * @return The module.
   */
  java.lang.String getModule();
  /**
   * <pre>
   * </pre>
   *
   * <code>string module = 1;</code>
   * @return The bytes for module.
   */
  com.google.protobuf.ByteString
      getModuleBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <pre>
   * </pre>
   *
   * <code>string filename = 2;</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <pre>
   * </pre>
   *
   * <code>.assets.EmbeddedScriptLanguage language = 3;</code>
   * @return The enum numeric value on the wire for language.
   */
  int getLanguageValue();
  /**
   * <pre>
   * </pre>
   *
   * <code>.assets.EmbeddedScriptLanguage language = 3;</code>
   * @return The language.
   */
  tools.elide.assets.EmbeddedScriptLanguage getLanguage();

  /**
   * <pre>
   * </pre>
   *
   * <code>.crypto.HashAlgorithm hash_algorithm = 4;</code>
   * @return The enum numeric value on the wire for hashAlgorithm.
   */
  int getHashAlgorithmValue();
  /**
   * <pre>
   * </pre>
   *
   * <code>.crypto.HashAlgorithm hash_algorithm = 4;</code>
   * @return The hashAlgorithm.
   */
  tools.elide.crypto.HashAlgorithm getHashAlgorithm();

  /**
   * <pre>
   * </pre>
   *
   * <code>bytes fingerprint = 5;</code>
   * @return The fingerprint.
   */
  com.google.protobuf.ByteString getFingerprint();

  /**
   * <pre>
   * </pre>
   *
   * <code>.assets.EmbeddedScriptMetadata metadata = 6;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <pre>
   * </pre>
   *
   * <code>.assets.EmbeddedScriptMetadata metadata = 6;</code>
   * @return The metadata.
   */
  tools.elide.assets.EmbeddedScriptMetadata getMetadata();
  /**
   * <pre>
   * </pre>
   *
   * <code>.assets.EmbeddedScriptMetadata metadata = 6;</code>
   */
  tools.elide.assets.EmbeddedScriptMetadataOrBuilder getMetadataOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_modified = 7;</code>
   * @return Whether the lastModified field is set.
   */
  boolean hasLastModified();
  /**
   * <pre>
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_modified = 7;</code>
   * @return The lastModified.
   */
  com.google.protobuf.Timestamp getLastModified();
  /**
   * <pre>
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_modified = 7;</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastModifiedOrBuilder();

  /**
   * <pre>
   * </pre>
   *
   * <code>string sourcemap = 8;</code>
   * @return The sourcemap.
   */
  java.lang.String getSourcemap();
  /**
   * <pre>
   * </pre>
   *
   * <code>string sourcemap = 8;</code>
   * @return The bytes for sourcemap.
   */
  com.google.protobuf.ByteString
      getSourcemapBytes();
}
