// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/assets/embedded.proto

package tools.elide.assets;

public final class Embedded {
  private Embedded() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_EmbeddedScriptMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_EmbeddedScriptMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_EmbeddedScriptMetadata_JsScriptMetadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_EmbeddedScriptMetadata_JsScriptMetadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_assets_EmbeddedScript_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_assets_EmbeddedScript_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033elide/assets/embedded.proto\022\006assets\032\037g" +
      "oogle/protobuf/timestamp.proto\032\031elide/cr" +
      "ypto/crypto.proto\032\025elide/data/data.proto" +
      "\"\304\002\n\026EmbeddedScriptMetadata\022E\n\njavascrip" +
      "t\030\001 \001(\0132/.assets.EmbeddedScriptMetadata." +
      "JsScriptMetadataH\000\032\326\001\n\020JsScriptMetadata\022" +
      "N\n\005level\030\001 \001(\0162?.assets.EmbeddedScriptMe" +
      "tadata.JsScriptMetadata.JsLanguageLevel\"" +
      "r\n\017JsLanguageLevel\022\035\n\031JS_LANGUAGE_LEVEL_" +
      "DEFAULT\020\000\022\007\n\003ES5\020\001\022\007\n\003ES6\020\002\022\n\n\006ES2017\020\003\022" +
      "\n\n\006ES2018\020\004\022\n\n\006ES2019\020\005\022\n\n\006ES2020\020\006B\n\n\010m" +
      "etadata\"\240\002\n\016EmbeddedScript\022\016\n\006module\030\001 \001" +
      "(\t\022\020\n\010filename\030\002 \001(\t\0220\n\010language\030\003 \001(\0162\036" +
      ".assets.EmbeddedScriptLanguage\022-\n\016hash_a" +
      "lgorithm\030\004 \001(\0162\025.crypto.HashAlgorithm\022\023\n" +
      "\013fingerprint\030\005 \001(\014\0220\n\010metadata\030\006 \001(\0132\036.a" +
      "ssets.EmbeddedScriptMetadata\0221\n\rlast_mod" +
      "ified\030\007 \001(\0132\032.google.protobuf.Timestamp\022" +
      "\021\n\tsourcemap\030\010 \001(\t*:\n\026EmbeddedScriptLang" +
      "uage\022\030\n\024LANGUAGE_UNSPECIFIED\020\000\022\006\n\002JS\020\001B\227" +
      "\001\n\022tools.elide.assetsH\001P\001Z5github.com/el" +
      "ide-tools/elide/assets/embedded;embedded" +
      "\330\001\001\370\001\001\242\002\003ELD\252\002\014Elide.Assets\272\002\005Elide\302\002\003EL" +
      "D\312\002\014Elide\\Assets\352\002\rElide::Assetsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          tools.elide.crypto.Crypto.getDescriptor(),
          tools.elide.data.Data.getDescriptor(),
        });
    internal_static_assets_EmbeddedScriptMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_assets_EmbeddedScriptMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_EmbeddedScriptMetadata_descriptor,
        new java.lang.String[] { "Javascript", "Metadata", });
    internal_static_assets_EmbeddedScriptMetadata_JsScriptMetadata_descriptor =
      internal_static_assets_EmbeddedScriptMetadata_descriptor.getNestedTypes().get(0);
    internal_static_assets_EmbeddedScriptMetadata_JsScriptMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_EmbeddedScriptMetadata_JsScriptMetadata_descriptor,
        new java.lang.String[] { "Level", });
    internal_static_assets_EmbeddedScript_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_assets_EmbeddedScript_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_assets_EmbeddedScript_descriptor,
        new java.lang.String[] { "Module", "Filename", "Language", "HashAlgorithm", "Fingerprint", "Metadata", "LastModified", "Sourcemap", });
    com.google.protobuf.TimestampProto.getDescriptor();
    tools.elide.crypto.Crypto.getDescriptor();
    tools.elide.data.Data.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
