// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elide/assets/embedded.proto

package tools.elide.assets;

public interface EmbeddedScriptMetadataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:assets.EmbeddedScriptMetadata)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * </pre>
   *
   * <code>.assets.EmbeddedScriptMetadata.JsScriptMetadata javascript = 1;</code>
   * @return Whether the javascript field is set.
   */
  boolean hasJavascript();
  /**
   * <pre>
   * </pre>
   *
   * <code>.assets.EmbeddedScriptMetadata.JsScriptMetadata javascript = 1;</code>
   * @return The javascript.
   */
  tools.elide.assets.EmbeddedScriptMetadata.JsScriptMetadata getJavascript();
  /**
   * <pre>
   * </pre>
   *
   * <code>.assets.EmbeddedScriptMetadata.JsScriptMetadata javascript = 1;</code>
   */
  tools.elide.assets.EmbeddedScriptMetadata.JsScriptMetadataOrBuilder getJavascriptOrBuilder();

  public tools.elide.assets.EmbeddedScriptMetadata.MetadataCase getMetadataCase();
}
