name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
        experimental: [false]
        include:
          - os: ubuntu-latest
            experimental: false
          - os: macos-latest
            experimental: true
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      ## Setup: Repo
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3

      ## Setup: Java
      - uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # tag=v3
        with:
          distribution: 'zulu'
          java-version: '11'

      ## Setup: GraalVM
      - uses: elide-tools/setup-graalvm@48f2bf339ab7d35e31029b1822a213681fdfc42e # tag=5.0
        with:
          graalvm: '21.0.0.2'
          java: 'java11'
          arch: 'amd64'

      ## Setup: Gradle Caches
      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # tag=v2

      ## Prep: Download Caches
      - name: Cache build
        uses: actions/cache@9b0c1fce7a93df8e3bb8926b0d6e9d89e92f20a7 # tag=v3
        with:
          path: |
            ./build
            ./*/build
            ./*/*/build
          key: elide-${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            elide-gradle-${{ runner.os }}
            elide-gradle-

      ## Job: Run build
      - name: Run Gradle build
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # tag=v2
        with:
          arguments: |
            preMerge
            -Pelide.ci=true
            --scan
            --continue

      ## Job: Run plugin
      - name: Run the plugin
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # tag=v2
        if: success()
        with:
          arguments: |
            example:build
            -Pelide.ci=true
            --scan
            --continue

      ## CI: Build
      - name: "Failure reports"
        if: failure()
        uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # tag=v3
        with:
          name: failure-reports
          path: |
            build/reports/**/*.*

      ## Job: Verify plugin output (JS)
      - name: Verify plugin output (JS)
        if: success()
        run: |
          file ./example/fullstack/node/build/distributions/*.js
          grep -Fq "esbuild" ./example/fullstack/node/build/esbuild/esbuild.*.js

      ## Job: Verify plugin output (JVM)
      - name: Verify plugin output (JVM)
        if: success()
        run: |
          file ./example/fullstack/server/build/resources/main/embedded/embedded.assets*
          file ./example/fullstack/server/build/resources/main/embedded/*.js
          file ./example/fullstack/server/build/resources/main/assets/*.txt
          file ./example/fullstack/server/build/resources/main/assets/*.css
          file ./example/fullstack/server/build/resources/main/assets/*.js
