name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      GRADLE_PUBLISH_KEY: ${{ secrets.GRADLE_PUBLISH_KEY }}
      GRADLE_PUBLISH_SECRET: ${{ secrets.GRADLE_PUBLISH_SECRET }}
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3
      - name: Cache Gradle Caches
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # tag=v2
      - name: Run Gradle tasks
        run: ./gradlew preMerge --continue --dependency-verification=lenient
      - name: Publish on Plugin Portal
        run: ./gradlew --info --project-dir plugin-build setupPluginUploadFromEnvironment publishPlugins --dependency-verification=lenient
        if: success()
